### PR TITLE
Import in ur readme

### PR DESCRIPTION
**Pull request by hraffiest**
Import in ur readme from recaptcha lib, isnt it?

### CODE REVIEW

**Comment by jake-walker** [comment]
Please could you rebase your pull request onto the latest changes to get rid of the old commits. [This guide](https://anavarre.net/how-to-rebase-a-github-pull-request/) should be of help.

**Comment by hraffiest** [comment]
sorry for chaos in ur lib) Its my first steps. Thank u for ur explanations

**Comment by jake-walker** [comment]
Hi @hraffiest, I've added in a comment which disables the style error on the line you added in `__init__.py` and fixed a slight issue with it. Thanks for the PR!

**Comment by jake-walker** [comment]
Now live on PyPI: https://pypi.org/project/wtforms-hcaptcha/0.1.3/

**Comment by hraffiest** [comment]
Thank u for good experience)

**Pull request merged**
